services:
  app:
    image: tennisfolio
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
    networks:
      - tennisnet

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tennisnet
    depends_on:
      - app

networks:
  tennisnet: