services:
  app:
    image: tennisfolio:latest
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/tennisfolio
      SPRING_DATASOURCE_USERNAME: tennisfolio
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties
      - /var/log/tennisfolio:/var/log/tennisfolio
    networks:
      - tennisnet
    depends_on:
      - redis
      - mariadb
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tennisnet
    depends_on:
      - app
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    networks:
        - tennisnet

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: tennisfolio
      MARIADB_USER: tennisfolio
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - tennisnet
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--storage.tsdb.retention.time=1d'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tennisnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - tennisnet

volumes:
  grafana_data:
  redis_data:
  mariadb_data:

networks:
  tennisnet: