services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tennisfolio:local
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/application.properties
      TZ: "Asia/Seoul"
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties:ro
    networks:
      - monitoring
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"  # 로컬 접근도 허용 (optional)
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  grafana_data:
  redis_data: {}

networks:
  monitoring: