-- 클럽 등급 관리 도입용 DDL
-- 적용 전, 기존 SKILL_NOTE 데이터 수를 확인한다.
-- SELECT COUNT(*) AS skill_note_count
-- FROM tb_club_member
-- WHERE SKILL_NOTE IS NOT NULL AND TRIM(SKILL_NOTE) <> '';

CREATE TABLE tb_club_skill_tier (
  CLUB_SKILL_TIER_ID BIGINT NOT NULL AUTO_INCREMENT,
  CLUB_ID BIGINT NOT NULL,
  NAME VARCHAR(10) NOT NULL,
  LEVEL INT NOT NULL,
  CRT_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPD_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CLUB_SKILL_TIER_ID),
  CONSTRAINT uk_club_skill_tier_name UNIQUE (CLUB_ID, NAME),
  CONSTRAINT uk_club_skill_tier_level UNIQUE (CLUB_ID, LEVEL),
  CONSTRAINT fk_club_skill_tier_club
    FOREIGN KEY (CLUB_ID) REFERENCES tb_club (CLUB_ID)
);

ALTER TABLE tb_club_member
  ADD COLUMN SKILL_TIER_ID BIGINT NULL;

ALTER TABLE tb_club_member
  ADD CONSTRAINT fk_club_member_skill_tier
    FOREIGN KEY (SKILL_TIER_ID) REFERENCES tb_club_skill_tier (CLUB_SKILL_TIER_ID);

ALTER TABLE tb_club_member
  DROP COLUMN SKILL_NOTE;
